Feature: Draft coin comparison charts
agreen254/crypto-app pull request #7
Opened 2024-03-02 05:56 UTC by agreen254

https://github.com/agreen254/crypto-app/assets/101513222/c232ca1a-e8c5-4125-9eac-356133e95e3c

2024-03-04 15:12 UTC, yoloOnTheBattlefield requested changes

2024-03-04 15:12 UTC, yoloOnTheBattlefield commented on app/api/v1/comparison/route.ts
> +  const fetchBody = `${id}/market_chart?vs_currency=${currency}&days=${days}`;
const fetchHead = "https://api.coingecko.com/api/v3/coins";
  const fetchBody = `/${id}/market_chart?vs_currency=${currency}&days=${days}`;

we usually put the / in the next string

2024-03-04 15:12 UTC, yoloOnTheBattlefield commented on app/api/v1/comparison/route.ts
> +  }).catch((e) => (error = e));
the default is get

2024-03-04 15:12 UTC, yoloOnTheBattlefield commented on app/api/v1/comparison/route.ts
> +  }).catch((e) => (error = e));
maybe don;t use `.catch` and make a `try catch` around your code

2024-03-04 15:12 UTC, yoloOnTheBattlefield commented on components/ComparisonCharts/ComparisonChartsWrapper.tsx
> +      )}
use filter then map, and make sure you use a key in your map

2024-03-09 00:26 UTC, agreen254 commented
https://github.com/agreen254/crypto-app/assets/101513222/821a7aae-f48b-4017-ab08-00591edbf89a

2024-03-11 21:52 UTC, merged